development: &non_production_conf
  :google_analytics:
    :api_key: "blah"
  :site:
    :title: "Walkable.me"
    :address: "http://localhost:4567/"

test:
  <<: *non_production_conf

production:
  :google_analytics:
    :api_key: "blah blee"
  :site:
    :title: "Walkable.me"
    :address: "[Address]"

